### ISSUE TITLE
[FP] Killaura delay false flag

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#1004]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: General PvP and clicking
**Video of false positive**: http://matrix.zakshearman.com/2-7-3-killaura-false.mp4
**Other information**: Disabled velocity because of custom KB

## Configuration Files
**Link to checks.yml file**: Default with velocity set to enabled: false.

**Comment by jiangdashao** [comment]
1. This check can't be "fixed", because it works by checking for changes in the player's click interval. If you click with high CPS, you can get these false flags, because of the problem with Minecraft mechanism.
2. The check was designed for minigame server or survival server, if you are running it in a PVP server, you can disable this check
