### ISSUE TITLE
[BYPASS] nosaddle

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1464]
**Server version**:1.15.2 
**Hacked client**: wwe
**Link to hacked client**: 
**Cheat that bypassed**: nosaddle 
**Video of bypass**: not really needed
**Other information**: turn on entity ride and choose ride without saddle, the horse will move where you want it to whether it is tamed or not. There is a nosaddle check but it only works when the player is using entity speed.

**Comment by rasputinea** [comment]
it seems to trigger nosaddle if i go up blocks. But it happens very inconsistantly

**Comment by rasputinea** [comment]
also nosaddle check should be insta-kicks since its impossible to ride a horse without a saddle

**Comment by rasputinea** [comment]
and it should be its own module (vehicle.nosaddle)

**Comment by WaterTheMelon** [comment]
When a hacker **joins** with vanilla fly or anti-hunger **on** then turning on fly it doesn't set a back point for the plugin to rubber band the player to. I could tell this is what the issue was when I could turn up fly and move very quickly with the plugin only moving me to the ground if I get too far off the ground if I turn fly off and back on again without disconnecting it then sets a back point and I get properly rubber banded.

**Comment by jiangdashao** [comment]
But the horse moves by itself, telling me how can I tell if the horse is moving on its own or a player-controlled move

**Comment by rasputinea** [comment]
https://youtu.be/b4QL5Xeu9ck it seems like nosaddle check in matrix works for fast horses but slower mules etc arent flagged, I made a check for it (https://pastebin.com/bY1niCKR) which I can assume is very similar to yours except my distance threshold is 0.1 and yours seems to be 0.2, so you could fix this by making yours 0.1, also please make a seperate module for nosaddle so i can adjust its vl, thanks!

**Comment by jiangdashao** [comment]
Weird, the no saddle check is not working for donkey
