### ISSUE TITLE
[REQUEST] Disable not checking GeyserMC players

### ISSUE THREAD

**Issue by gogorz** [jiangdashao/Matrix-Issues#1664]
**What features/checks do you need?:**
An option to not bypass checks for bedrock (Geyser) players.

**Comment by rasputinea** [comment]
yeah with sigma you can change client brand so ppl could maybe put client brand to GeyserMC then bypass or just use a bedrock client.

**Comment by rasputinea** [comment]
how about you look at what movement bedrock players are doing that is invalid and account for it.

**Comment by jiangdashao** [comment]
1. Bedrock uses a different protocol, so it's useless to change the client brand, The packet format is different. If you want to cheat Geysermc, you need to adapt to Bedrock's communication protocol, which is a huge workload.
2. If you check GeyserMC players, these players will get a lot of false positives because Bedrock is different from the Java version in many features

@rasputinea @gogorz
